version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run .

  frontend:
    build:
      context: ./frontend/swe-s25-project
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/swe-s25-project:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
